version: "3.8"

services:
  mongo1:
    image: mongo
    container_name: mongo1
    command:
      [
        "--replSet",
        "my-replica-set",
        "--bind_ip_all",
        "--port",
        "30001"
      ]
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - 30001:30001
    networks:
      - mongoCluster

  mongo2:
    image: mongo
    container_name: mongo2
    command:
      [
        "--replSet",
        "my-replica-set",
        "--bind_ip_all",
        "--port",
        "30002"
      ]
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - 30002:30002
    networks:
      - mongoCluster

  mongo3:
    image: mongo
    container_name: mongo3
    command:
      [
        "--replSet",
        "my-replica-set",
        "--bind_ip_all",
        "--port",
        "30003"
      ]
    volumes:
      - ./data/mongo-3:/data/db
    ports:
      - 30003:30003
    networks:
      - mongoCluster

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo1
      - ME_CONFIG_MONGODB_PORT=30001
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=local
    depends_on:
      - mongo1
    ports:
      - "8888:8081"
    networks:
      - mongoCluster

networks:
  mongoCluster: {}
